### ISSUE TITLE
DCW-exporter does not connect with the main DCW

### ISSUE THREAD

**Issue by edersong** [Palleri/DCW-exporter#2]
Hello,
the exporter is not connecting with the main DCW reporting the following error:
`psql: error: connection to server at "192.168.86.104", port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?`
Port 5432 was already opened on both hosts.

**Comment by Palleri** [comment]
Hi,
Can you provide me with your docker-compose files, both for the exporter and main DCW?
Make sure not to include any sensitive informations such as tokens or if you have a notify URL applied on main DCW.

**Comment by edersong** [comment]
Hi Palleri,
Sure...
DCW:
```dockerfile
version: '3.2'
services:
  dcw:
    container_name: dcw
    image: 'palleri/dcw:latest'
    restart: unless-stopped
    hostname: cheetara
    ports:
      - '8089:80'
    volumes:
      - dcw:/var/www/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TOKEN: password
      CRON_TIME: "08:00"
volumes:
  dcw:
    name: dcw
``` 
dcw-exporter:
```dockerfile
version: '3.2'
services:
  dcw-exporter:
    container_name: dcw-exporter
    hostname: tygra
    image: palleri/dcw-exporter:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      TOKEN: password
      MAIN_DCW: 192.168.86.204
```

**Comment by Palleri** [comment]
The main dcw needs to have the port 5432 applied under ports.

```
    ports:
      - '8089:80'
      - '5432:5432'
```
My syntax could be wrong here, im on my phone so do not copy paste xD

**Comment by edersong** [comment]
Hi, @Palleri 
It worked, thank you!!
Please, update the readme to reflect this setting accordingly.
You're making a wonderful work on this tool and I'm happy to see how it's progressing.
As a suggestion, please, provide release information through the releases tag, because it will be more easy to follow the changes, test them and report bugs. 😉

**Comment by Palleri** [comment]
Fantastic.  
Ye, I already updated the main dcw with the missing information about the ports. My bad.

Thank you for the feedback.  
I will try to have patchnotes somehow.  
Good idea about tags, will make use of them.
Im marking this as solved. You are more than welcome to suggest more features or ideas in the future.

**Comment by julez2310** [comment]
Hi @all. I'm experiencing the same problem as shown from @edersong. I added the ports in the compose file, but the exporter won't connect to the main dcw. Any other suggestions?

**Comment by julez2310** [comment]
Edit: I'm getting a different error now: psql: error: connection to server at "192.168.178.163", port 5432 failed: FATAL:  password authentication failed for user "postgres"

**Comment by Palleri** [comment]
Hi, have you the token set in both DCW and DCW-exporter compose files?

Could you please paste your compose files !!**without**!! the token or any sensitive information regarding notifications.

```yml
    environment:
      TOKEN: superSecretPassw0rd                        // required // Main DCW token
````

**Comment by julez2310** [comment]
Hi Palleri,
sorry for the late response. I think I've figured it out. It was my zoken I guess, because once I wrote it between two single apostrophe, it worked for me. Like this:
   
```
environment:
      TOKEN: 'superSecretPassw0rd'                        // required // Main DCW token
```
Maybe it has something to do with a "*" in my Token?
