### ISSUE TITLE
Stops Exporting After DCW Host Reboot

### ISSUE THREAD

**Issue by robklingler** [Palleri/DCW-exporter#3]
When starting from scratch, I have been able to set up DCW in one server and DCW-exporter in another server, and everything works correctly.

However, after rebooting the server with DCW installed, DCW now only shows the host server and not anything from the server with DCW-exporter on it.

Happy to share more information, but not sure what would be useful.  Logs for DCW-exporter are as follows:

```shell
# Starting Dockcheck-Exporter
# This might take a while, it depends on how many containers are running #
Will send information to 10.0.0.10
Connected to 10.0.0.10
Exporter already exists in database; continue
``` 

I've since stopped and restarted both the DCW and DCW-exporter containers, but nothing changes.  I experienced this once before and ultimately got everything syncing again... but now I don't remember how.

**Comment by robklingler** [comment]
Stopped and started the DCW stack in Portainer (as opposed to just the container) and the DCW-exporter host showed up again.

**Comment by Palleri** [comment]
Hi, sorry for my absence.
If the exporter lose connection to the main dcw, its better to restart and let the main start up fully before starting the exporter.
